_commit: v1.12.1-6-gbf0c0a5
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageDescription: Password Manager
homepageEnabled: true
homepageGroup: Tools
homepageIcon: vaultwarden
homepageName: Vault Warden
ingHost: vault.crt.house
ingName: vault-warden
ingress: false
labels: |-
  app.kubernetes.io/component: vault-warden
  app.kubernetes.io/name: vault-warden
name: vault-warden
namespace: vault-warden
pvc: true
pvcAccessMode: ReadWriteOnce
pvcName: vault-warden
pvcSize: 15Gi
pvcStorageClass: nfs-critical
reloader: true
resources:
- configmaps.yaml
- deployments.yaml
- ingresses.yaml
- pvcs.yaml
- rbac.yaml
- service-accounts.yaml
- services.yaml
service: false
serviceAccount: true
svcAccountName: vault-warden
upstreamURL: https://github.com/dani-garcia/vaultwarden
url: https://github.com/charlesthomas/homelab-vault-warden
