---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-warden
  namespace: vault-warden
spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 15Gi
    storageClassName: nfs-crticial
    volumeMode: Filesystem
