---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-warden
  namespace: vault-warden
  labels:
    
    
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: nfs-critical
  volumeMode: Filesystem
